### PR TITLE
Improve selectors

### LINKED ISSUE #12: need to support non-numeric passage values
E.g. See Plato's Apology 17a-42a

### PR DESCRIPTION
**Pull request by PonteIneptique**
Should fix #12 #13 #14 #15 
@balmas Could you have a check on your side before I merge ?

### CODE REVIEW

**Comment by balmas** [comment]
This works (it's live at http://sosol.perseids.org/exist/rest/db/app/treebank-entertext-arethusa-stage.xhtml?) and is probably more functional than what I've had before, but there are some caveats.

1) I think if the call to validPassage drops off the end passage because it wasn't bigger we should at least notify the user that what was retrieve was just the start passage. But see below.

2) we will eventually get into trouble with the check to see if the end is bigger. This is something that I misunderstood in my initial implementation of the CTS API .. the spec apparently says nothing about whether the citation values can be compared, and the range implementation is supposed to be purely based on document order. I'm pretty sure you will find that this is a difference between the CTS 3 and CTS 5 implementations, i.e the latter will accept 1.5.-1.1 as a valid range as long as 1.1 comes after 1.5 in the document.  I can see the rationale for this (particularly in order to support citation identifiers that can't be easily compared) but I think in 90% of the cases the citations ARE sequential, and so having some checking of this is in fact useful.  We should probably make this optional though and not kill ourselves to get it right. (e.g. I think we could also assume that we might have non-latin chars as the alpha part of the citation string, but I think it's not worth going crazy over this).  One option might just be to do the check and warn the user if we think it might not right be but not override their input.

**Comment by PonteIneptique** [comment]
Question is then : should I add an option to check sequentiality or just remove everything ?

**Comment by balmas** [comment]
I am torn on this point. It  might be simplest to remove it.

**Comment by PonteIneptique** [comment]
I think with the error handling, its indeed not necessary anymore

**Pull request merged**
